# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abe Land
title: Senior Staff Software Engineer

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  abeland
facebook_username: abe
instagram_username: abe_land
linkedin_username: abe-land-9001047

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: tl;dr
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello. I’m Abe Land.

  I'm an entrepreneur and software engineering generalist with experience working in many areas from security to infrastructure to iOS to Ruby/Rails web apps.

  I've made web apps, backend services, and mobile apps.

  I love moving bits around!

  I've also lead dozens of teams technically in all stages from proof of concept, primary architecture, expansion plans, mentoring new tech leads, etc. I really enjoy leading teams from just an idea to a fully launched product/project while helping engineers grow their careers and skills along the way.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instagram / Meta
        link: instagram.com
        sub_title: Senior Staff Software Engineer
        caption: November 2018 - Present
        description: | # this will include new lines to allow paragraphs

          I am the tech lead for Instagram Direct Messaging infrastructure and was also the lead architect and engineer for [cross-app communication between IG Direct messaging and Facebook messenger](https://about.fb.com/news/2020/09/new-messaging-features-for-instagram/).

      - layout: left
        title: Ardius (acquired by Gusto)
        link: ardius.com
        sub_title: Co-founder and CTO
        caption: September 2017 - October 2018
        description: | # this will include new lines to allow paragraphs

          **[acquired by Gusto](https://gusto.com/company-news/welcoming-ardius-to-gusto){:target="_blank"} in 2021**

          I was a co-founder and the CTO of Ardius. I architected all and implemented most of the backend systems for the first version of the R&D credit tool which was used in production successfully for many clients. I also co-architected and implemented a lot of the frontend (reactJS).

          Some public things that I made during this time for Ardius:

          1. [Discretion](https://github.com/abeland/discretion){:target="_blank"}

             A privacy/authorization framework for Ruby on Rails applications

          2. [GRR](https://github.com/abeland/grrr){:target="_blank"}

             A template for a fully-functional Ruby/Rails/ReactJS/GraphQL application

          3. [omniauth-quickbooks-oauth2](https://github.com/abeland/omniauth-quickbooks-oauth2){:target="_blank"}

             An omniauth strategy allowing authentication via Intuit’s OAuth2 flow

          4. [apollo_fetch_upload_rails_middleware](https://github.com/abeland/apollo_fetch_upload_rails_middleware){:target="_blank"}

             A fast and efficient server implementation of multipart file uploading via GraphQL mutations using the Apollo React framework against a Rails application (before you had to base64 encode file contents which of course is inefficient)

      - layout: left
        title: Facebook (now Meta)
        link: facebook.com
        sub_title: Staff Software Engineer
        caption: April 2011 - August 2017, Menlo Park
        description: |

          I worked on **a lot** of products and teams at Facebook and as a tech lead a few times. Some highlights:

          1. Site Integrity

             I helped build the infrastructure for fighting spam all across the site. The infra I built fought fake accounts, phishing, malware, commercial spam, and many other forms of attacks.

          2. Notifications

             I was the tech lead on a team that built the experimental [Facebook Here](https://techcrunch.com/2015/10/26/facebook-nowtifications/){:target="_blank"} product

          3. [K-12 Education Initiative](https://newsroom.fb.com/news/2015/09/introducing-facebook-and-summits-k-12-education-project/){:target="_blank"}

             I was a senior engineer on the Facebook partnership with Summit Public Schools. We built software for teachers and students which was used to create and facilitate a personalized learning experience in schools

      - layout: left
        title: Facebook (now Meta)
        link: facebook.com
        sub_title: Software Engineering Intern
        caption: June 2006 - September 2006, Palo Alto
        description: | # this will include new lines to allow paragraphs

          I worked on the Social Plugins team where I helped improve several social plugins including the Like Button and Comments Plugin.

          I also built the [Send Button](https://code.facebook.com/posts/172718822914973/building-the-send-button/.){:target="_blank"}

          At the end of my internship, I was offered a full-time position.

      - layout: left
        title: Stanford Computer Science Department
        link: cs.stanford.edu
        sub_title: Course Assistant
        caption: September 2009 - March 2011, Stanford
        description: | # this will include new lines to allow paragraphs

          I planned and taught sections, graded papers, and held office hours for _CS105: Introduction to Computer Science for Non-Majors_.

      - layout: left
        title: Stanford Center for Professional Development
        link: scpd.stanford.edu
        sub_title: Software Developer
        caption: September 2007 - April 2008, Stanford
        description: | # this will include new lines to allow paragraphs

          I did general web coding and also designed and built a new, non-Flash video player interface for SCPD which students used to watch recorded Stanford course lectures.

      - layout: left
        title: Efficient Frontier
        sub_title: Engineering Intern
        caption: June 2006 - September 2006, Mountain View
        description: | # this will include new lines to allow paragraphs

          I designed and built a search engine mining framework which generated statistics around internet keyword searches. This data was then used to augment the company’s core algorithms.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stanford University
        caption: 2009-2011
        sub_title: MS Computer Science
        description:
          + GPA&#58; 3.846

          + Specialization&#58; Computer Networking and Security
      - layout: left
        title: Stanford University
        caption: 2004 - 2008
        sub_title: BS Computer Science
        description:
          + GPA&#58; 3.781 cumulative, 3.826 in the major

          + Tau Beta Pi Engineering Honor Society, Gamma Chapter

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs

      I love computer science and software engineering, both theory and practice. I love building software in general. When I'm not building software, I also like:

      #### Climbing

      I mostly climb indoors but sometimes [I go out and get humbled on real rock](https://www.mountainproject.com/user/112504014/abe-land?action=ticks&){:target="_blank"}. I mostly enjoy sport climbing but my friends drag me bouldering sometimes.

      #### Coffee

      Coffee is great. Aside from helping you wake up and get focused, [it helps you poop](https://www.washingtonpost.com/news/speaking-of-science/wp/2015/08/10/why-does-coffee-make-you-poop/){:target="_blank"}, [might prevent Alzheimer’s/dementia](https://pubmed.ncbi.nlm.nih.gov/20182054/){:target="_blank"}, and [has a bunch of other benefits](https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/coffee-and-health/faq-20058339){:target="_blank"}. Also it tastes amazing. I love roasting, brewing, tasting, and reading about coffee.

      #### Being a dad
      My wife and I are blessed with two wonderful children who bring us equal parts confusion and frustration but also much much more joy.

      #### DYI home improvement
      I have no idea what I'm doing here but it's tons of fun.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
